apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: k8s-experiment
  labels:
    app: k8s-experiment
    group: backend
spec:
  selector:
    app: k8s-experiment
    group: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      name: app
