apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: k8s-experiment
  labels:
    app: k8s-experiment
    group: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-experiment
      group: frontend
  template:
    metadata:
      labels:
        app: k8s-experiment
        group: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/roelofr/k8s-experiment/frontend-app:edge
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: ghcr
